function brightness-off
	osascript -e 'tell application "System Events"' -e 'key code 145' -e ' end tell'	
	osascript -e 'tell application "System Events"' -e 'key code 145' -e ' end tell'	
	osascript -e 'tell application "System Events"' -e 'key code 145' -e ' end tell'	
	osascript -e 'tell application "System Events"' -e 'key code 145' -e ' end tell'	
	osascript -e 'tell application "System Events"' -e 'key code 145' -e ' end tell'	
	osascript -e 'tell application "System Events"' -e 'key code 145' -e ' end tell'	
	osascript -e 'tell application "System Events"' -e 'key code 145' -e ' end tell'	
	osascript -e 'tell application "System Events"' -e 'key code 145' -e ' end tell'	
	osascript -e 'tell application "System Events"' -e 'key code 145' -e ' end tell'	
	osascript -e 'tell application "System Events"' -e 'key code 145' -e ' end tell'	
	osascript -e 'tell application "System Events"' -e 'key code 145' -e ' end tell'	
	osascript -e 'tell application "System Events"' -e 'key code 145' -e ' end tell'	
	osascript -e 'tell application "System Events"' -e 'key code 145' -e ' end tell'	
	osascript -e 'tell application "System Events"' -e 'key code 145' -e ' end tell'	
	osascript -e 'tell application "System Events"' -e 'key code 145' -e ' end tell'	
	osascript -e 'tell application "System Events"' -e 'key code 145' -e ' end tell'	
end
